name: Build Flutter SDK for Windows ARM64

on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"
permissions:
 contents: write
 
jobs:
  build-windows-arm64:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Git (ensure available in PATH)
        run: git --version

      - name: Clone Flutter SDK
        run: |
          git clone https://github.com/flutter/flutter.git --branch stable --depth 1
          cd flutter
          git rev-parse --short HEAD

      - name: Bootstrap Flutter (installs Dart SDK)
        run: |
          cd flutter
          .\bin\flutter.bat --version
      
      - name: Pre-cache Flutter engine artifacts
        run: |
          cd flutter
          .\bin\flutter.bat precache --windows
          .\bin\flutter.bat precache --web
          .\bin\flutter.bat precache --android
          
      - name: Verify Dart SDK bootstrap
        run: |
          cd flutter
          if (Test-Path ".\bin\cache\dart-sdk\bin\dart.exe") {
            .\bin\cache\dart-sdk\bin\dart.exe --version
          } else {
            Write-Host "❌ Dart SDK not found!"
            exit 1
                }
      - name: Get Flutter version
        run: |
          $FLUTTER_VERSION = Get-Content flutter\bin\internal\version
          echo "FLUTTER_VERSION=$FLUTTER_VERSION" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Verify Flutter engine binaries are ARM64
        run: |
          cd flutter
          function Get-MachineType($path) {
            $bytes = Get-Content $path -Encoding Byte -TotalCount 1000
            $peOffset = [BitConverter]::ToInt32($bytes[60..63],0)
            $machine = [BitConverter]::ToUInt16($bytes[($peOffset+4)..($peOffset+5)],0)
            return $machine
          }

          $arm64 = 0xAA64
          $x64   = 0x8664
          $x86   = 0x14c

          $binaries = Get-ChildItem -Recurse -Include *.exe,*.dll bin\cache\artifacts\engine\windows-arm64

          foreach ($bin in $binaries) {
            try {
              $machine = Get-MachineType $bin.FullName
              switch ($machine) {
                $arm64 { Write-Host "✅ ARM64: $($bin.FullName)" }
                $x64   { Write-Host "❌ x64 engine binary found: $($bin.FullName)"; exit 1 }
                $x86   { Write-Host "❌ x86 engine binary found: $($bin.FullName)"; exit 1 }
                default { Write-Host "⚠ Unknown arch ($machine): $($bin.FullName)"; exit 1 }
              }
            } catch {
              Write-Host "⚠ Non-PE file skipped: $($bin.FullName)"
            }
          }

          Write-Host "✅ All Flutter engine binaries are ARM64"
            
      - name: Package SDK
        run: |
          cd flutter
          Compress-Archive -Path * -DestinationPath ../flutter_windows_arm64_sdk.zip -Force

      - name: Upload Artifact (CI artifact, not release yet)
        uses: actions/upload-artifact@v4
        with:
          name: flutter_windows_arm64_sdk
          path: flutter_windows_arm64_sdk.zip

      - name: Publish SDK to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "flutter-${{ env.FLUTTER_VERSION }}-${{ github.run_number }}-windows-arm64"
          name: "Flutter ${{ env.FLUTTER_VERSION }} Windows ARM64 SDK"
          files: flutter_windows_arm64_sdk.zip
          body: |
            This release provides a Flutter SDK build for **Windows ARM64**.

            ✅ Includes:
            - Dart SDK (currently x64, runs under emulation)
            - Flutter CLI
            - Windows ARM64 engine binaries
            - Web SDK artifacts
            - Android engine artifacts

            ⚠️ Dart is x64 because upstream Dart does not yet publish Windows ARM64 builds.
            Flutter engine is ARM64-native.

            💡 Please test on real hardware and share feedback to help improve the Windows ARM64 Flutter experience.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
