name: Build Flutter SDK for Windows ARM64

on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"
permissions:
 contents: write
 
jobs:
  build-windows-arm64:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Git (ensure available in PATH)
        run: git --version

      - name: Clone Flutter SDK
        run: |
          git clone https://github.com/flutter/flutter.git --branch stable --depth 1
          cd flutter
          git rev-parse --short HEAD

      - name: Bootstrap Flutter (installs Dart SDK)
        run: |
          cd flutter
          .\bin\flutter.bat --version

      - name: Verify Dart SDK bootstrap
        run: |
          cd flutter
          if (Test-Path ".\bin\cache\dart-sdk\bin\dart.exe") {
            .\bin\cache\dart-sdk\bin\dart.exe --version
          } else {
            Write-Host "❌ Dart SDK not found!"
            exit 1
          }

      - name: Check binary architecture (ensure ARM64)
        run: |
          cd flutter
          $dartPath = ".\bin\cache\dart-sdk\bin\dart.exe"
          if (Test-Path $dartPath) {
            $output = & $env:SystemRoot\System32\where.exe dart.exe
            Write-Host "Dart path: $output"
            $arch = (Get-Item $dartPath).VersionInfo
            Write-Host "Dart File Version: $($arch.FileVersion)"
            # TODO: Replace with a more robust ARM64 check if needed
          } else {
            Write-Host "❌ Dart binary not found for arch check"
            exit 1
          }

      - name: Package SDK
        run: |
          cd flutter
          Compress-Archive -Path * -DestinationPath ../flutter_windows_arm64_sdk.zip -Force

      - name: Upload Artifact (CI artifact, not release yet)
        uses: actions/upload-artifact@v4
        with:
          name: flutter_windows_arm64_sdk
          path: flutter_windows_arm64_sdk.zip

      - name: Publish SDK to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Flutter Windows ARM64 SDK ${{ github.ref_name }}
          body: "Prebuilt **Flutter Windows ARM64 SDK**.\n\n⚠️ Note: May contain quirks, please test and report issues."
          files: flutter_windows_arm64_sdk.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
