name: Build Flutter SDK for Windows ARM64

on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"
permissions:
 contents: write
 
jobs:
  build-windows-arm64:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Git (ensure available in PATH)
        run: git --version

      - name: Clone Flutter SDK
        run: |
          git clone https://github.com/flutter/flutter.git --branch stable --depth 1
          cd flutter
          git rev-parse --short HEAD

      - name: Bootstrap Flutter (installs Dart SDK)
        run: |
          cd flutter
          .\bin\flutter.bat --version

      - name: Verify Dart SDK bootstrap
        run: |
          cd flutter
          if (Test-Path ".\bin\cache\dart-sdk\bin\dart.exe") {
            .\bin\cache\dart-sdk\bin\dart.exe --version
          } else {
            Write-Host "❌ Dart SDK not found!"
            exit 1
          }

      - name: Verify Flutter/Dart binaries are ARM64
        run: |
          cd flutter
          function Get-MachineType($path) {
            $bytes = Get-Content $path -Encoding Byte -TotalCount 1000
            $peOffset = [BitConverter]::ToInt32($bytes[60..63],0)
            $machine = [BitConverter]::ToUInt16($bytes[($peOffset+4)..($peOffset+5)],0)
            return $machine
          }

          $arm64 = 0xAA64
          $x64   = 0x8664
          $x86   = 0x14c

          $binaries = Get-ChildItem -Recurse -Include *.exe,*.dll bin\cache

          foreach ($bin in $binaries) {
            try {
              $machine = Get-MachineType $bin.FullName
              switch ($machine) {
                $arm64 { Write-Host "✅ ARM64: $($bin.FullName)" }
                $x64   { Write-Host "❌ x64 binary found: $($bin.FullName)"; exit 1 }
                $x86   { Write-Host "❌ x86 binary found: $($bin.FullName)"; exit 1 }
                default { Write-Host "⚠ Unknown arch ($machine): $($bin.FullName)"; exit 1 }
              }
            } catch {
              Write-Host "⚠ Non-PE file skipped: $($bin.FullName)"
            }
          }

          Write-Host "✅ All Dart/Flutter PE binaries are ARM64"

      - name: Package SDK
        run: |
          cd flutter
          Compress-Archive -Path * -DestinationPath ../flutter_windows_arm64_sdk.zip -Force

      - name: Upload Artifact (CI artifact, not release yet)
        uses: actions/upload-artifact@v4
        with:
          name: flutter_windows_arm64_sdk
          path: flutter_windows_arm64_sdk.zip

      - name: Publish SDK to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Flutter Windows ARM64 SDK ${{ github.ref_name }}
          body: "Prebuilt **Flutter Windows ARM64 SDK**.\n\n⚠️ Note: May contain quirks, please test and report issues."
          files: flutter_windows_arm64_sdk.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
